In [1]:
import pandas as pd
import numpy as np
import random as rnd
import matplotlib.pyplot as plt
import scipy
import math
from scipy import stats
stats.chisqprob = lambda chisq, df: stats.chi2.sf(chisq,df)
import statsmodels.api as sm

d:\python-installed\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [2]:
AirQualityCat = ['air-qual-good','air-qual-moderate','air-qual-unhealthy','air-qual-hazardous']
WeatherCat = ['weather-rainy','weather-stormy','weather-sunny','weather-cloudy','weather-hot','weather-cold','weather-dry','weather-wet','weather-windy','weather-snow']
TrafficCat = ['traffic-low','traffic-moderate','traffic-high','traffic-worse']
DayPartCat = ['dt-early-morning','dt-morning','dt-noon','dt-afternoon','dt-night','dt-late-night']
BikeLanesCat = ['bl-none','bl-partial','bl-full']
TemperatureCat = ['t-0-10','t-10-14','t-14-18','t-18-21','t-21-25','t-25-30','t-30-40','t-40-60','t-60-80','t-80-100']
ModesCat = ['mode-car','mode-transit','mode-bike','mode-mt-bike','mode-walk']

In [5]:
CatCombined = []
CatCombined.extend(AirQualityCat)
CatCombined.extend(WeatherCat)
CatCombined.extend(TrafficCat)
CatCombined.extend(DayPartCat)
CatCombined.extend(BikeLanesCat)
CatCombined.extend(TemperatureCat)

In [17]:
IndCombined = []
IndCombined.extend(CatCombined)
CatCombined.extend(ModesCat)

In [31]:

def ConvertTemperature(intValue,tempCategories):
    outArr = [0]*len(tempCategories)
    myVal = math.floor(intValue/len(tempCategories) - 1)
    outArr[myVal] = 1
    return outArr

def ConvertAirQuality(intValue,aqCategories):
    outArr = [0]*len(aqCategories)
    myVal = math.ceil((intValue / 2.5) - 1)
    outArr[myVal] = 1
    return outArr
    

In [42]:
xFile = pd.ExcelFile('data.xlsx')
df = xFile.parse('data')
dataArr = np.ones((len(IndCombined),len(ModesCat)))
for i in range(len(df.index)):
    freshVal = int(df.iloc[i]['Freshness'])
    freshVal = freshVal * 10
    tAirQual = ConvertAirQuality(int(df.iloc[i]['air-quality']),AirQualityCat)
    tWeather = df.iloc[i]['weather']
    tTraffic = df.iloc[i]['traffic']
    tDayTime = df.iloc[i]['day-time']
    tBikeLanes = df.iloc[i]['bike-lane']
    tTemperature = ConvertTemperature(int(df.iloc[i]['temperature']),TemperatureCat)
    tMode = df.iloc[i]['mode']
    tModeIndex = ModesCat.index(tMode);
    tAirQualIndex = tAirQual.index(1)
    tWeatherIndex = IndCombined.index(tWeather)
    tTrafficIndex = IndCombined.index(tTraffic)
    tDayTimeIndex = IndCombined.index(tDayTime)
    tBikeLanesIndex = IndCombined.index(tBikeLanes)
    
    dataArr[tAirQualIndex][tModeIndex] = freshVal + dataArr[tAirQualIndex][tModeIndex]
    dataArr[tWeatherIndex][tModeIndex] = freshVal + dataArr[tWeatherIndex][tModeIndex]
    dataArr[tTrafficIndex][tModeIndex] = freshVal + dataArr[tTrafficIndex][tModeIndex]
    dataArr[tDayTimeIndex][tModeIndex] = freshVal + dataArr[tDayTimeIndex][tModeIndex]
    dataArr[tBikeLanesIndex][tModeIndex] = freshVal + dataArr[tBikeLanesIndex][tModeIndex]
    

print(dataArr)


[[3.010e+02 2.310e+02 3.410e+02 4.810e+02 5.010e+02]
 [6.810e+02 4.010e+02 6.010e+02 9.410e+02 4.210e+02]
 [4.810e+02 6.110e+02 4.810e+02 3.110e+02 8.410e+02]
 [7.610e+02 6.310e+02 1.051e+03 5.610e+02 8.410e+02]
 [5.010e+02 2.610e+02 2.510e+02 2.110e+02 1.810e+02]
 [3.410e+02 2.310e+02 4.310e+02 2.210e+02 3.210e+02]
 [3.310e+02 6.100e+01 6.100e+01 3.510e+02 2.610e+02]
 [4.310e+02 2.210e+02 2.010e+02 2.910e+02 5.110e+02]
 [1.410e+02 3.610e+02 3.310e+02 2.710e+02 5.010e+02]
 [1.810e+02 3.410e+02 3.110e+02 2.910e+02 1.810e+02]
 [1.110e+02 6.100e+01 4.910e+02 4.210e+02 3.010e+02]
 [1.910e+02 3.410e+02 4.010e+02 2.410e+02 3.510e+02]
 [1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [5.810e+02 2.610e+02 6.210e+02 7.310e+02 1.211e+03]
 [5.210e+02 4.410e+02 6.210e+02 5.710e+02 2.310e+02]
 [5.210e+02 4.810e+02 3.910e+02 4.310e+02 3.810e+02]
 [6.010e+02 6.910e+02 8.410e+02 5.610e+02 7.810e+02]
 [3.410e+02 2.310e+02 4.910e+02 3.310e+02 2.21

In [ ]:
def ConvertTemperature(intValue,tempCategories):
    outArr = [0]*len(tempCategories)
    myVal = math.floor(intValue/len(tempCategories))
    outArr[myVal] = 1
    return outArr

In [ ]:
ConvertTemperature(99,TemperatureCat)

In [ ]:
def ConvertAirQuality(intValue,aqCategories):
    outArr = [0]*len(aqCategories)
    myVal = math.ceil((intValue / 2.5) - 1)
    outArr[myVal] = 1
    return outArr

In [ ]:
ConvertAirQuality(6,AirQualityCat)